### ISSUE TITLE
themes

### ISSUE THREAD

**Issue by bnidevs** [bnidevs/the-hotbox#68]
- make halloween theme (orange + black , somethin like that)

- make footer theme selector a dropdown choice
like this:
```
<select name="cars" id="cars">
  <option value="volvo">Volvo</option>
  <option value="saab">Saab</option>
  <option value="mercedes">Mercedes</option>
  <option value="audi">Audi</option>
</select>
```

**Comment by bnidevs** [comment]
while you're at it, add christmas and thanksgiving too

**Comment by bnidevs** [comment]
and new years

**Comment by bernep** [comment]
I'd recommend moving the "Dark Mode" checkbox to the themes as well. So we add a "Dark Theme" on top of the other themes and remove the "Dark Mode" checkbox.

**Comment by bernep** [comment]
Also, we could potentially use JS to select a default theme temporarily using the current day if it is a holiday.

**Comment by bnidevs** [comment]
> I'd recommend moving the "Dark Mode" checkbox to the themes as well. So we add a "Dark Theme" on top of the other themes and remove the "Dark Mode" checkbox.

This is what i meant

**Comment by bnidevs** [comment]
> Also, we could potentially use JS to select a default theme temporarily using the current day if it is a holiday.

this is a good idea

**Comment by bnidevs** [comment]
Fix christmas + thanksgiving theme + add date checker
