### ISSUE TITLE
Microsoft Edge Problem never see preview

### ISSUE THREAD

**Issue by ikyman** [bnidevs/the-hotbox#90]
So I am on Microsoft Edge, and I uploaded a video, but the rectangle showing what I assume would be the deep-fried video says "No Preview Available"

**To Reproduce**
1. Be on Microsoft Edge
2. Upload a video
3. Click upload & wait
4.  Boom
![image](https://user-images.githubusercontent.com/70716489/106183872-d1421d80-616e-11eb-8fb3-0382ab320358.png)

**Comment by ikyman** [comment]
LMAO forgot the upload button

**Comment by bnidevs** [comment]
submit a pull request solving this issue via aws ecr and lambda

i was not able to accomplish it

my furthest attempts are in the deployment folder

thanks

**Comment by bnidevs** [comment]
copy of #50
